use std::fs;
use std::path::{Path, PathBuf};

mod prolink;
mod sentinel;
mod ble_beacon;
mod serato_sqlite;
mod lan_handoff;

#[tauri::command]
fn read_text_file(path: String) -> Result<String, String> {
    fs::read_to_string(&path).map_err(|e| e.to_string())
}

#[tauri::command]
fn read_binary_file(path: String) -> Result<Vec<u8>, String> {
    fs::read(&path).map_err(|e| e.to_string())
}

fn music_dir() -> Option<PathBuf> {
    if let Ok(profile) = std::env::var("USERPROFILE") {
        return Some(PathBuf::from(profile).join("Music"));
    }
    if let Ok(home) = std::env::var("HOME") {
        return Some(PathBuf::from(home).join("Music"));
    }
    None
}

fn ensure_parent_dir(path: &Path) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Writes the "Q Requests" m3u8 playlist with the given accepted track paths.
/// Returns the absolute path of the playlist so we can show it in the UI.
#[tauri::command]
fn write_q_requests_playlist(track_paths: Vec<String>) -> Result<String, String> {
    let dir = music_dir().ok_or_else(|| "Could not locate the Music folder.".to_string())?;
    let file = dir.join("Q Requests.m3u8");
    ensure_parent_dir(&file)?;

    let mut content = String::from("#EXTM3U\n");
    content.push_str("# Generated by Q — your live booth queue. Open this file in Serato or Rekordbox.\n");
    for p in track_paths {
        let trimmed = p.trim();
        if trimmed.is_empty() {
            continue;
        }
        content.push_str(trimmed);
        content.push('\n');
    }
    fs::write(&file, content).map_err(|e| e.to_string())?;
    Ok(file.to_string_lossy().to_string())
}

/// Encodes a string as UTF-16 big-endian for Serato .crate files.
fn utf16_be(s: &str) -> Vec<u8> {
    let mut out = Vec::with_capacity(s.len() * 2);
    for unit in s.encode_utf16() {
        out.extend_from_slice(&unit.to_be_bytes());
    }
    out
}

fn serato_tag(tag: &[u8; 4], value: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(8 + value.len());
    out.extend_from_slice(tag);
    out.extend_from_slice(&(value.len() as u32).to_be_bytes());
    out.extend_from_slice(value);
    out
}

/// Serato stores `ptrk` paths relative to the drive root with forward slashes
/// and no drive letter. e.g. `C:\Users\ayesh\Music\song.mp3` → `Users/ayesh/Music/song.mp3`.
fn serato_relative_path(absolute: &str) -> String {
    let s = absolute.replace('\\', "/");
    // Strip "C:/" or any drive-letter prefix.
    if s.len() >= 3 {
        let bytes = s.as_bytes();
        if bytes[1] == b':' && (bytes[2] == b'/' || bytes[2] == b'\\') {
            return s[3..].to_string();
        }
    }
    // macOS absolute paths start with "/" — leave them as-is minus the leading slash.
    s.trim_start_matches('/').to_string()
}

/// Writes a binary Serato `.crate` so the named crate auto-appears in Serato's
/// sidebar with the given track paths. Returns the crate path on success.
#[tauri::command]
fn write_serato_q_requests_crate(track_paths: Vec<String>) -> Result<String, String> {
    let mut subcrates = None;
    if let Ok(profile) = std::env::var("USERPROFILE") {
        subcrates = Some(PathBuf::from(profile).join("Music").join("_Serato_").join("Subcrates"));
    } else if let Ok(home) = std::env::var("HOME") {
        subcrates = Some(PathBuf::from(home).join("Music").join("_Serato_").join("Subcrates"));
    }
    let subcrates = subcrates.ok_or_else(|| "Could not locate the Serato Subcrates folder.".to_string())?;
    if !subcrates.is_dir() {
        return Err("Serato Subcrates folder not found — open Serato once to create it.".to_string());
    }
    let crate_path = subcrates.join("Q Requests.crate");

    let mut buf: Vec<u8> = Vec::new();
    // vrsn — Serato's required header. Value is UTF-16BE.
    buf.extend_from_slice(&serato_tag(b"vrsn", &utf16_be("1.0/Serato ScratchLive Crate")));

    for absolute in track_paths {
        let trimmed = absolute.trim();
        if trimmed.is_empty() {
            continue;
        }
        let rel = serato_relative_path(trimmed);
        let ptrk = serato_tag(b"ptrk", &utf16_be(&rel));
        buf.extend_from_slice(&serato_tag(b"otrk", &ptrk));
    }

    fs::write(&crate_path, buf).map_err(|e| e.to_string())?;
    Ok(crate_path.to_string_lossy().to_string())
}

#[tauri::command]
fn list_crate_files(dir: String) -> Result<Vec<String>, String> {
    let entries = fs::read_dir(&dir).map_err(|e| e.to_string())?;
    let mut files: Vec<String> = entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "crate"))
        .map(|p| p.to_string_lossy().to_string())
        .collect();
    files.sort();
    Ok(files)
}

#[tauri::command]
fn detect_serato_subcrates() -> Option<String> {
    serato_subcrates_candidates()
        .into_iter()
        .find(|p| p.is_dir())
        .map(|p| p.to_string_lossy().to_string())
}

#[tauri::command]
fn detect_rekordbox_xml() -> Option<String> {
    let candidates = rekordbox_candidates();
    candidates
        .into_iter()
        .find(|p| p.exists())
        .map(|p| p.to_string_lossy().to_string())
}

/// Returns the Pioneer/rekordbox folder path even if `rekordbox.xml` isn't
/// there yet — used to point the manual file picker at the right starting
/// directory. DJs would otherwise navigate into their music folder looking
/// for the XML, since `%APPDATA%` is hidden by default on Windows.
#[tauri::command]
fn rekordbox_pioneer_dir() -> Option<String> {
    if let Ok(appdata) = std::env::var("APPDATA") {
        let dir = PathBuf::from(&appdata).join("Pioneer").join("rekordbox");
        if dir.is_dir() {
            return Some(dir.to_string_lossy().to_string());
        }
    }
    if let Ok(home) = std::env::var("HOME") {
        let dir = PathBuf::from(&home)
            .join("Library")
            .join("Pioneer")
            .join("rekordbox");
        if dir.is_dir() {
            return Some(dir.to_string_lossy().to_string());
        }
    }
    None
}

fn rekordbox_candidates() -> Vec<PathBuf> {
    let mut paths = Vec::new();

    if let Ok(appdata) = std::env::var("APPDATA") {
        let base = PathBuf::from(&appdata).join("Pioneer").join("rekordbox");
        paths.push(base.join("rekordbox.xml"));
        paths.push(base.join("share.xml"));
    }

    if let Ok(home) = std::env::var("HOME") {
        let base = PathBuf::from(&home)
            .join("Library")
            .join("Pioneer")
            .join("rekordbox");
        paths.push(base.join("rekordbox.xml"));
        paths.push(base.join("share.xml"));
    }

    paths
}

fn serato_history_sessions_dir() -> Option<PathBuf> {
    serato_history_sessions_candidates()
        .into_iter()
        .find(|p| p.is_dir())
}

fn serato_history_sessions_candidates() -> Vec<PathBuf> {
    let mut paths = Vec::new();

    if let Ok(profile) = std::env::var("USERPROFILE") {
        paths.push(
            PathBuf::from(&profile)
                .join("Music")
                .join("_Serato_")
                .join("History")
                .join("Sessions"),
        );
    }

    if let Ok(home) = std::env::var("HOME") {
        paths.push(
            PathBuf::from(&home)
                .join("Music")
                .join("_Serato_")
                .join("History")
                .join("Sessions"),
        );
    }

    paths
}

/// First non-loopback IPv4 for QR codes (phone on same Wi‑Fi).
#[tauri::command]
fn get_lan_ipv4() -> Option<String> {
    use std::net::UdpSocket;
    let socket = UdpSocket::bind("0.0.0.0:0").ok()?;
    socket.connect("8.8.8.8:80").ok()?;
    let ip = socket.local_addr().ok()?.ip();
    if ip.is_loopback() || !ip.is_ipv4() {
        return None;
    }
    Some(ip.to_string())
}

fn serato_database_v2_path() -> Option<PathBuf> {
    music_dir().map(|m| m.join("_Serato_").join("database V2"))
}

/// Serato library database bytes (`Music/_Serato_/database V2`) for BPM/key enrichment.
#[tauri::command]
fn read_serato_database_v2() -> Option<Vec<u8>> {
    let path = serato_database_v2_path()?;
    fs::read(&path).ok()
}

fn serato_session_files_newest_first() -> Vec<PathBuf> {
    let Some(dir) = serato_history_sessions_dir() else {
        return Vec::new();
    };
    let mut files: Vec<(std::time::SystemTime, PathBuf)> = Vec::new();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(_) => return Vec::new(),
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("session") {
            continue;
        }
        if let Ok(modified) = entry.metadata().and_then(|m| m.modified()) {
            files.push((modified, path));
        }
    }
    files.sort_by(|a, b| b.0.cmp(&a.0));
    files.into_iter().map(|(_, p)| p).collect()
}

/// Paths to recent Serato history `.session` files (newest first).
#[tauri::command]
fn list_serato_recent_sessions(limit: Option<usize>) -> Vec<String> {
    let take = limit.unwrap_or(3).min(10);
    serato_session_files_newest_first()
        .into_iter()
        .take(take)
        .map(|p| p.to_string_lossy().to_string())
        .collect()
}

/// Latest Serato history session bytes (most recently modified .session file).
#[tauri::command]
fn get_serato_latest_session() -> Option<Vec<u8>> {
    let path = serato_session_files_newest_first().into_iter().next()?;
    fs::read(&path).ok()
}

fn serato_subcrates_candidates() -> Vec<PathBuf> {
    let mut paths = Vec::new();

    if let Ok(profile) = std::env::var("USERPROFILE") {
        paths.push(
            PathBuf::from(&profile)
                .join("Music")
                .join("_Serato_")
                .join("Subcrates"),
        );
    }

    if let Ok(home) = std::env::var("HOME") {
        paths.push(
            PathBuf::from(&home)
                .join("Music")
                .join("_Serato_")
                .join("Subcrates"),
        );
    }

    paths
}

/// Native OS drag — drop a local audio file onto Serato / Rekordbox decks.
#[tauri::command]
fn start_file_drag(window: tauri::WebviewWindow, path: String) -> Result<(), String> {
    let trimmed = path.trim();
    if trimmed.is_empty() {
        return Err("No file path.".to_string());
    }
    let p = PathBuf::from(trimmed);
    if !p.is_file() {
        return Err("Track file not found on disk. Import your library so Q knows local paths.".to_string());
    }
    let abs = p.canonicalize().map_err(|e| e.to_string())?;

    let icon_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("icons/32x32.png");
    let preview_icon = drag::Image::File(icon_path);

    let (tx, rx) = std::sync::mpsc::channel();
    let w = window.clone();
    window
        .run_on_main_thread(move || {
            let result = drag::start_drag(
                &w,
                drag::DragItem::Files(vec![abs]),
                preview_icon,
                |_result, _pos| {},
                drag::Options::default(),
            );
            let _ = tx.send(result);
        })
        .map_err(|e| e.to_string())?;

    match rx.recv() {
        Ok(Ok(())) => Ok(()),
        Ok(Err(e)) => Err(e.to_string()),
        Err(_) => Err("Drag operation failed.".to_string()),
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            read_text_file,
            read_binary_file,
            list_crate_files,
            detect_rekordbox_xml,
            rekordbox_pioneer_dir,
            detect_serato_subcrates,
            read_serato_database_v2,
            get_serato_latest_session,
            list_serato_recent_sessions,
            serato_sqlite::get_serato_sqlite_history,
            get_lan_ipv4,
            write_q_requests_playlist,
            write_serato_q_requests_crate,
            start_file_drag,
            ble_beacon::start_ble_beacon,
            ble_beacon::stop_ble_beacon,
            ble_beacon::ble_beacon_status,
            prolink::prolink_request_status,
            sentinel::detect_dj_software_running,
            lan_handoff::start_lan_handoff,
            lan_handoff::get_lan_pairing_info,
        ]);
    prolink::install(builder)
        .run(tauri::generate_context!())
        .expect("error while running Q");
}
