#!/usr/bin/env node
/**
 * Sync LAN URLs from Q_CROWD_URL in root .env → VITE_Q_CROWD_LAN_URL,
 * EXPO_PUBLIC_* (booth), and apps/booth/.env for phone testing.
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");

function parseEnv(text) {
  const map = new Map();
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i < 1) continue;
    map.set(t.slice(0, i).trim(), t.slice(i + 1).trim());
  }
  return map;
}

function serializeEnv(lines, updates) {
  const keys = new Set(updates.keys());
  const out = [];
  const seen = new Set();

  for (const line of lines) {
    const t = line.trim();
    if (!t || t.startsWith("#")) {
      out.push(line);
      continue;
    }
    const i = t.indexOf("=");
    if (i < 1) {
      out.push(line);
      continue;
    }
    const key = t.slice(0, i).trim();
    if (updates.has(key)) {
      out.push(`${key}=${updates.get(key)}`);
      seen.add(key);
    } else {
      out.push(line);
    }
  }

  for (const [key, val] of updates) {
    if (!seen.has(key)) out.push(`${key}=${val}`);
  }
  return out.join("\n").replace(/\n*$/, "\n");
}

if (!existsSync(envPath)) {
  console.error("No .env at repo root. Copy .env.example first.");
  process.exit(1);
}

const raw = readFileSync(envPath, "utf8");
const lines = raw.split(/\r?\n/);
const env = parseEnv(raw);
const crowdUrl = env.get("Q_CROWD_URL") || "http://localhost:5173";

let host;
let port = "5173";
try {
  const u = new URL(crowdUrl);
  host = u.hostname;
  port = u.port || (u.protocol === "https:" ? "443" : "80");
} catch {
  console.error("Invalid Q_CROWD_URL:", crowdUrl);
  process.exit(1);
}

const isLocal = host === "localhost" || host === "127.0.0.1";
if (isLocal) {
  console.log(
    "Q_CROWD_URL is localhost. Set Q_CROWD_URL=http://<your-lan-ip>:5173 in .env (ipconfig), then re-run.",
  );
  process.exit(0);
}

const apiLan = `http://${host}:8787`;
const crowdLan = `http://${host}:${port}`;

const rootUpdates = new Map([
  ["VITE_Q_CROWD_LAN_URL", crowdLan],
  ["EXPO_PUBLIC_Q_API_URL", apiLan],
  ["EXPO_PUBLIC_Q_CROWD_URL", crowdLan],
]);

writeFileSync(envPath, serializeEnv(lines, rootUpdates), "utf8");

const boothEnv = `# Auto-generated by npm run sync:env — LAN testing on a physical phone
EXPO_PUBLIC_Q_API_URL=${apiLan}
EXPO_PUBLIC_Q_CROWD_URL=${crowdLan}
`;
writeFileSync(join(root, "apps/booth/.env"), boothEnv, "utf8");

console.log("Synced LAN dev env:");
console.log("  API (phone):", apiLan);
console.log("  Crowd:", crowdLan);
console.log("  VITE_Q_CROWD_LAN_URL → desktop QR");
console.log("  apps/booth/.env → Expo");
