#!/usr/bin/env node
/**
 * Sync LAN URLs from Q_CROWD_URL in root .env → VITE_Q_CROWD_LAN_URL,
 * EXPO_PUBLIC_* (booth), and apps/booth/.env for phone testing.
 *
 * When Q_CROWD_URL is localhost, auto-detects the first non-internal IPv4
 * address (Windows/macOS/Linux) and updates Q_CROWD_URL before syncing.
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { networkInterfaces } from "os";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");

function parseEnv(text) {
  const map = new Map();
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i < 1) continue;
    map.set(t.slice(0, i).trim(), t.slice(i + 1).trim());
  }
  return map;
}

function serializeEnv(lines, updates) {
  const keys = new Set(updates.keys());
  const out = [];
  const seen = new Set();

  for (const line of lines) {
    const t = line.trim();
    if (!t || t.startsWith("#")) {
      out.push(line);
      continue;
    }
    const i = t.indexOf("=");
    if (i < 1) {
      out.push(line);
      continue;
    }
    const key = t.slice(0, i).trim();
    if (updates.has(key)) {
      out.push(`${key}=${updates.get(key)}`);
      seen.add(key);
    } else {
      out.push(line);
    }
  }

  for (const [key, val] of updates) {
    if (!seen.has(key)) out.push(`${key}=${val}`);
  }
  return out.join("\n").replace(/\n*$/, "\n");
}

function detectLanIp() {
  const nets = networkInterfaces();
  const candidates = [];

  for (const ifaces of Object.values(nets)) {
    for (const net of ifaces ?? []) {
      const family = net.family === "IPv4" || net.family === 4;
      if (!family || net.internal) continue;
      if (net.address.startsWith("169.254.")) continue;
      candidates.push(net.address);
    }
  }

  // Prefer typical home LAN ranges
  const preferred = candidates.find(
    (a) => a.startsWith("192.168.") || a.startsWith("10.") || /^172\.(1[6-9]|2\d|3[01])\./.test(a),
  );
  return preferred ?? candidates[0] ?? null;
}

if (!existsSync(envPath)) {
  console.error("No .env at repo root. Copy .env.example first.");
  process.exit(1);
}

let raw = readFileSync(envPath, "utf8");
let lines = raw.split(/\r?\n/);
let env = parseEnv(raw);
let crowdUrl = env.get("Q_CROWD_URL") || "http://localhost:5173";

let host;
let port = "5173";
try {
  const u = new URL(crowdUrl);
  host = u.hostname;
  port = u.port || (u.protocol === "https:" ? "443" : "80");
} catch {
  console.error("Invalid Q_CROWD_URL:", crowdUrl);
  process.exit(1);
}

const isLocal = host === "localhost" || host === "127.0.0.1";
if (isLocal) {
  const lanIp = detectLanIp();
  if (!lanIp) {
    console.log(
      "Q_CROWD_URL is localhost and no LAN IP was found. Connect to Wi‑Fi/Ethernet, or set Q_CROWD_URL=http://<your-ip>:5173 manually.",
    );
    process.exit(0);
  }
  crowdUrl = `http://${lanIp}:${port || "5173"}`;
  const crowdUpdate = new Map([["Q_CROWD_URL", crowdUrl]]);
  raw = serializeEnv(lines, crowdUpdate);
  writeFileSync(envPath, raw, "utf8");
  lines = raw.split(/\r?\n/);
  env = parseEnv(raw);
  host = lanIp;
  console.log("Auto-detected LAN IP → Q_CROWD_URL=" + crowdUrl);
}

const apiLan = `http://${host}:8787`;
const crowdLan = crowdUrl.includes("://") ? crowdUrl : `http://${host}:${port}`;

const rootUpdates = new Map([
  ["VITE_Q_CROWD_LAN_URL", crowdLan],
  ["EXPO_PUBLIC_Q_API_URL", apiLan],
  ["EXPO_PUBLIC_Q_CROWD_URL", crowdLan],
]);

writeFileSync(envPath, serializeEnv(lines, rootUpdates), "utf8");

const boothEnv = `# Auto-generated by npm run sync:env — LAN testing on a physical phone
EXPO_PUBLIC_Q_API_URL=${apiLan}
EXPO_PUBLIC_Q_CROWD_URL=${crowdLan}
`;
writeFileSync(join(root, "apps/booth/.env"), boothEnv, "utf8");

const crowdMobileEnv = `# Auto-generated by npm run sync:env
EXPO_PUBLIC_Q_CROWD_URL=${crowdLan}
`;
writeFileSync(join(root, "apps/crowd-mobile/.env"), crowdMobileEnv, "utf8");

console.log("Synced LAN dev env:");
console.log("  API (phone):", apiLan);
console.log("  Crowd:", crowdLan);
console.log("  VITE_Q_CROWD_LAN_URL → desktop QR");
  console.log("  apps/booth/.env → Expo DJ");
  console.log("  apps/crowd-mobile/.env → Expo Crowd (guest iOS)");
